services:
  reverse-proxy:
    image: nginx:1.23.4-alpine
    volumes:
      - /home/ubuntu/reverse-proxy/certs:/etc/letsencrypt
      - /home/ubuntu/reverse-proxy/www:/var/www/html
      - /home/ubuntu/cod2/servers:/mnt/servers
    configs:
      - source: nginx
        target: /etc/nginx/nginx.conf
    ports:
      - target: 443
        published: 443
        protocol: tcp
      - target: 80
        published: 80
        protocol: tcp
    deploy:
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
  
  certbot-renew:
    image: certbot/certbot:latest
    volumes:
      - /home/ubuntu/reverse-proxy/certs:/etc/letsencrypt
      - /home/ubuntu/reverse-proxy/www:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - LETS_ENCRYPT_DOMAINS=${LETS_ENCRYPT_DOMAINS}
      - LETS_ENCRYPT_EMAIL=${LETS_ENCRYPT_EMAIL}
    entrypoint: "/bin/sh"
    command: >
      -c "apk add --no-cache docker-cli &&
      trap exit TERM; 
      sleep 30;
      while :; do
        echo \"$$(date): Expanding the certificate to $${LETS_ENCRYPT_DOMAINS}...\";
        certbot certonly --webroot --webroot-path=/var/www/html --cert-name mynl.pl --expand --keep-until-expiring --non-interactive --agree-tos --email $${LETS_ENCRYPT_EMAIL} -d $${LETS_ENCRYPT_DOMAINS} --deploy-hook 'docker service update --force reverse-proxy_reverse-proxy';
        echo \"$$(date): Starting certificate renewal check...\";
        certbot renew --webroot --webroot-path=/var/www/html --deploy-hook 'docker service update --force reverse-proxy_reverse-proxy';
        echo \"$$(date): Renewal check complete. Next check in 24 hours.\";
        sleep 24h & wait $$!;
      done;"
    deploy:
      restart_policy:
        condition: any
        delay: 10s

configs:
  nginx:
    name: nginx_${CONFIG_HASH}
    file: nginx.conf

networks:
  default:
    name: stack_network
    external: true
