name: Deploy shutdown-logs

on:
  push:
    branches: [master]
    paths:
      - "stacks/shutdown-logs/**"
      - ".github/workflows/deploy-shutdown-logs.yml"
      - ".github/workflows/deploy-stack.yml"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-stack.yml
    with:
      stack: shutdown-logs
    secrets: inherit
