name: Deploy livemap

on:
  push:
    branches: [master]
    paths:
      - "stacks/livemap/**"
      - ".github/workflows/deploy-livemap.yml"
      - ".github/workflows/deploy-stack.yml"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-stack.yml
    with:
      stack: livemap
    secrets: inherit
