name: shutdown-logs Continuous Integration

on:
  push:
    branches: [master]
    paths:
      - 'infra/services/shutdown-logs/**'
      - '.github/workflows/infra-shutdown-logs.yml'
  workflow_dispatch:

env:
  WorkingDir: infra/services/shutdown-logs
  StackName: shutdown-logs

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy ${{ env.StackName }}
        working-directory: ${{ env.WorkingDir}}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          echo "Host *
            StrictHostKeyChecking no" > ~/.ssh/config

          ssh-agent bash -c '
            set -e
            ssh-add ~/.ssh/key
            docker context create temp --docker "host=ssh://${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}" && docker context use temp

            SHUTDOWN_LOGS_SCRIPT_HASH=$(sha256sum shutdown_logs.sh | cut -c1-12) \
            SHUTDOWN_LOGS_DISCORD_WEBHOOK=${{ secrets.SHUTDOWN_LOGS_DISCORD_WEBHOOK }} \
              docker stack deploy --resolve-image changed -c compose.yml ${{ env.StackName }}
            docker context rm temp -f
          '
   
          rm -f ~/.ssh/key
